name: Daily Post
on:
  schedule:
    - cron: '0 * * * *'  # 매시간 0분마다 실행 (UTC 기준)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install openai python-frontmatter pyyaml
      - name: Generate post
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/generate_post.py
      - name: Commit & Push
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore(post): daily article $(date -u '+%Y-%m-%d')"

          # 혹시 다른 커밋이 사이에 들어왔으면 받아서 리베이스 후 푸시
          git pull --rebase origin "${{ github.ref_name }}" || true
          git push origin HEAD:"${{ github.ref_name }}"